config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :vocises, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>

<h3>Owner of the site: Kutay Demireren</h3>
<h3>Contact at: kutay.demireren@outlook.com</h3>

<h4>Too excited to start? Okay, lets begin than;</h4>
<p>You can begin with creating a user with following
  <%= link_to 'this link', signup_path %> or a vocise with following
  <%= link_to 'this link', new_vocise_path %> </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Need Help?</h1>
<p>Please contact with Kutay Demireren, owner of this little app, at kutay.demireren@outlook.com</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
<h1>Vocision</h1>
<h3>Uncertainty? Vote for decision</h3>

<p> This is an application where you can decide with asking your friends.
  Instead of asking everyone individually, why don't you just ask from this app?
  Simple to use, simple to ask.</p>

  <% unless logged_in? %>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
  <% end %>


  <h5>Learn the details in  <%= link_to 'About', about_path %> page.</h5>

<h5><%= link_to 'Need Help?', help_path %></h5>
</div>