config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :vocises, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vocises, dependent: :destroy

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  validates :surname, presence: true, length: { maximum: 50 }

  validates :username, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @vocises = @user.vocises.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the Vocision App!"
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "Profile was successfully updated."
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = "User was successfully deleted."
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :surname, :username, :email, :password, :password_confirmation)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    flash[:danger] = "You are not allowed to perform this action." unless current_user?(@user)
    redirect_to(users_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :surname %>
    <%= f.text_field :surname %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<td><%= user.name %></td>
<td><%= user.surname %></td>
<td><%= user.username %></td>
<td><%= user.email %></td>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Account') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', user: @user%>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= link_to 'Profile', @user %> |
<%= link_to 'Back to Users', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%= render user %>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', user: @user %>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
    <h5>
      <strong>Name:</strong> <%= @user.name %>
    </h5>

    <h5>
      <strong>Surname:</strong> <%= @user.surname %>
    </h5>

    <h6>
      <strong>Email:</strong> <%= @user.email %>
    </h6>
  </aside>

  <div class="col-md-8">
    <% if @user.vocises.any? %>
        <h3>Vocises (<%= @user.vocises.count %>)</h3>
        <ol class="vocises">
          <%= render @vocises %>
        </ol>
        <%= will_paginate @vocises %>
    <% end %>
  </div>
</div>

<br>
<% if current_user?(@user) %>
    <%= link_to 'Create New Vocise!', new_vocise_path, class: 'btn btn-md btn-primary' %>
    <br>
    <br>
    <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>

<%= link_to 'Back', users_path %>