config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :vocises, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Vocision App</a>
    by <a href="https://www.linkedin.com/in/kutay-demireren">Kutay Demireren</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About',   about_path %></li>
      <li><%= link_to 'Help',   help_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Vocision App', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',    root_path %></li>
        <li><%= link_to 'About',   about_path %></li>
        <li><%= link_to 'Help',    help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Vocision</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>